
package client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AuthSvc", targetNamespace = "http://authsvc/", wsdlLocation = "http://demo.oracleads.com:7499/authsvc/AuthSvc?WSDL")
public class AuthSvc_Service
    extends Service
{

    private final static URL AUTHSVC_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(client.AuthSvc_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = client.AuthSvc_Service.class.getResource(".");
            url = new URL(baseUrl, "http://demo.oracleads.com:7499/authsvc/AuthSvc?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://demo.oracleads.com:7499/authsvc/AuthSvc?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AUTHSVC_WSDL_LOCATION = url;
    }

    public AuthSvc_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthSvc_Service() {
        super(AUTHSVC_WSDL_LOCATION, new QName("http://authsvc/", "AuthSvc"));
    }

    /**
     * 
     * @return
     *     returns AuthSvc
     */
    @WebEndpoint(name = "AuthSvcPort")
    public AuthSvc getAuthSvcPort() {
        return super.getPort(new QName("http://authsvc/", "AuthSvcPort"), AuthSvc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthSvc
     */
    @WebEndpoint(name = "AuthSvcPort")
    public AuthSvc getAuthSvcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://authsvc/", "AuthSvcPort"), AuthSvc.class, features);
    }

}
