
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthSvc", targetNamespace = "http://authsvc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthSvc {


    /**
     * 
     * @param userid
     * @param password
     * @return
     *     returns client.AuthInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://authsvc/", className = "client.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://authsvc/", className = "client.AuthenticateResponse")
    public AuthInfo authenticate(
        @WebParam(name = "userid", targetNamespace = "")
        String userid,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
